resources:
  - ../../base

namePrefix: prod-

images:
  - name: apiservice
    newTag: latest-prod

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: api-container
                env:
                  - name: ENV
                    value: "prod"
