apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lexmarkkubernetes/apiservice-prod:226beab601076482f00853eaa6539a6ed24958aa
          ports:
            - containerPort: 3001
