apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lexmarkkubernetes/apiservice-dev:92511c0380014159e8e084c6e43d06456709dcc0
          ports:
            - containerPort: 3001
