apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lexmarkkubernetes/apiservice-dev:d6f4f29e1042e9ded0467d413eb424ef13a41570
          ports:
            - containerPort: 3001
