apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lexmarkkubernetes/apiservice-staging:9cff55b330a4e06bd37eeb0174591c0e9d6b67c6
          ports:
            - containerPort: 3001
