apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: lexmarkkubernetes/apiservice-staging:8f3b9750cd286e0c0736fce1bcb87a5047e15aee
          ports:
            - containerPort: 3001
